### ISSUE TITLE
Difference in x-positioning definition

### ISSUE THREAD

**Issue by videophonegeek** [jbreckmckye/raphael-paragraph#3]
The default for raphael paper is text is centered at the percentage position:
var answer3 = paper.text("50%", "60", "YOUR GRANDPA BORN 1930's?");

raphael-paragraph interprets his as the leftmost position of the paragraph box
var answer4 = paper.paragraph({x : "50%", y : 96, text : "SUPPOSE YOU COUGH, GO DOCTOR YOU?"});

A challenge in implementation of centering for sure!

**Comment by jbreckmckye** [comment]
You should be able to center the text horizontally by passing the configuration

```
paper.paragraph({
    textStyle : {'text-anchor' : 'center'} 
    // will be merged into default textStyle for this element
});
```

I assumed most people would desire left-aligned text by default. It's true that the default behaviour of `paper.text` is to center the text horizontally, but it also centers the text vertically, which I don't think we'd want on a paragraph with potentially dynamic content. But I am open to changing this interface if it's confusing.

**Comment by videophonegeek** [comment]
text-anchor center will work for me. Defaults don't have to mirror Raphael.
