### ISSUE TITLE
Updating paragraph as text change

### ISSUE THREAD

**Issue by pomekrank** [jbreckmckye/raphael-paragraph#6]
Hi,

I'm having trouble trying to figure out a way to adjust the paragraph properties when text changed. For exemple if
`myText =  paper.paragraph({
      maxWidth : 125,
      text : "some text", 
      textStyle : {"font-family" : "Helvetica", "font-size" : 10} 
    });
`
and then after I've tried : 
`myText.attr({text: " Some new text"});`

It does change the text, put it maxWidth is not respected (and other properties as well). This is a simple exemple, but my problem involved multiple lines and more...

Thank you

**Comment by jbreckmckye** [comment]
Right now, you can't mutate a paragraph without re-rendering it. Sorry.
